from .games import boxing as boxing_v0
from .games import combat_tank as combat_tank_v0
from .games import combat_plane as combat_plane_v0
from .games import double_dunk as double_dunk_v0
from .games import entombed_competitive as entombed_competitive_v0
from .games import entombed_cooperative as entombed_cooperative_v0
from .games import flag_capture as flag_capture_v0
from .games import joust as joust_v0
from .games import ice_hockey as ice_hockey_v0
from .games import maze_craze as maze_craze_v0
from .games import mario_bros as mario_bros_v0
from .games import othello as othello_v0
from .games import pong_basketball as pong_basketball_v0
from .games import pong_classic as pong_classic_v0
from .games import pong_foozpong as pong_foozpong_v0
from .games import pong_quadrapong as pong_quadrapong_v0
from .games import pong_volleyball as pong_volleyball_v0
from .games import space_invaders as space_invaders_v0
from .games import space_war as space_war_v0
from .games import surround as surround_v0
from .games import tennis as tennis_v0
from .games import video_checkers as video_checkers_v0
from .games import wizard_of_wor as wizard_of_wor_v0
from .games import warlords as warlords_v0
