from pettingzoo.atari import (
    basketball_pong_v3,
    boxing_v2,
    combat_plane_v2,
    combat_tank_v2,
    double_dunk_v3,
    entombed_competitive_v3,
    entombed_cooperative_v3,
    flag_capture_v2,
    foozpong_v3,
    ice_hockey_v2,
    joust_v3,
    mario_bros_v3,
    maze_craze_v3,
    othello_v3,
    pong_v3,
    quadrapong_v4,
    space_invaders_v2,
    space_war_v2,
    surround_v2,
    tennis_v3,
    video_checkers_v4,
    volleyball_pong_v3,
    warlords_v3,
    wizard_of_wor_v3,
)
from pettingzoo.utils.deprecated_module import deprecated_handler

atari_environments = {
    "basketball_pong_v3": basketball_pong_v3,
    "boxing_v2": boxing_v2,
    "combat_tank_v2": combat_tank_v2,
    "combat_plane_v2": combat_plane_v2,
    "double_dunk_v3": double_dunk_v3,
    "entombed_competitive_v3": entombed_competitive_v3,
    "entombed_cooperative_v3": entombed_cooperative_v3,
    "flag_capture_v2": flag_capture_v2,
    "foozpong_v3": foozpong_v3,
    "joust_v3": joust_v3,
    "ice_hockey_v2": ice_hockey_v2,
    "maze_craze_v3": maze_craze_v3,
    "mario_bros_v3": mario_bros_v3,
    "othello_v3": othello_v3,
    "pong_v3": pong_v3,
    "quadrapong_v4": quadrapong_v4,
    "space_invaders_v2": space_invaders_v2,
    "space_war_v2": space_war_v2,
    "surround_v2": surround_v2,
    "tennis_v3": tennis_v3,
    "video_checkers_v4": video_checkers_v4,
    "volleyball_pong_v3": volleyball_pong_v3,
    "wizard_of_wor_v3": wizard_of_wor_v3,
    "warlords_v3": warlords_v3,
}


def __getattr__(env_name):
    return deprecated_handler(env_name, __path__, __name__)
