name: Automatic approve
on: pull_request_target

jobs:
  build:
    if: github.repository == 'FaramaFoundation/Pettingzoo'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.PAT }}
