name: Deploy Docs website
on:
  push:
    branches: [master]

jobs:
  docs:
    name: Generate Website
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install -r ./docs/requirements.txt && pip install .
      
      - name: Build
        run: sphinx-build -b dirhtml -v docs/source build

      - name: Move 404
        run: mv ./build/404/index.html ./build/404.html

      - name: Update 404 links
        run: python ./docs/scripts/move_404.py ./build/404.html

      - name: Remove .doctrees
        run: rm -r ./build/.doctrees

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build